from flask import Flask, render_template, send_file, send_from_directory
import os
import zipfile
import shutil

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/generate_blink')
def generate_blink():
    # Generate the Arduino code and zip it
    arduino_code = generate_arduino_code()
    zipped_code = zip_code(arduino_code)

    # Set the response headers for the zip file
    try:
        return send_file(zipped_code, as_attachment=True, download_name='blink.zip')
    finally:
        # Clean up the temporary directory
        temp_dir = os.path.join(os.path.dirname(__file__), 'temp')
        shutil.rmtree(temp_dir)

def generate_arduino_code():
    # Generate the Arduino code here
    # For example:
    arduino_code = """
    // Blink
    // Generated by Flask app

    void setup() {
      pinMode(13, OUTPUT);
    }

    void loop() {
      digitalWrite(13, HIGH);
      delay(1000);
      digitalWrite(13, LOW);
      delay(1000);
    }
    """
    return arduino_code

def zip_code(code):
    # Create a temporary directory to store the zipped file
    temp_dir = os.path.join(os.path.dirname(__file__), 'temp')
    os.makedirs(temp_dir, exist_ok=True)

    # Write the Arduino code to a file
    arduino_file = os.path.join(temp_dir, 'blink.ino')
    with open(arduino_file, 'w') as f:
        f.write(code)

    # Create the zip file
    zipped_file = os.path.join(temp_dir, 'blink.zip')
    with zipfile.ZipFile(zipped_file, 'w') as z:
        z.write(arduino_file, arcname='blink.ino')

    return zipped_file

if __name__ == '__main__':
    app.run(debug=True)
